= Build Scans Recipes Gradle Plugin
:buildscan-version: 1.2
:plugin-version: 0.1.2

image:http://img.shields.io/travis/melix/gradle-buildscan-recipes/master.svg["Build Status (travis)", link="https://travis-ci.org/melix/gradle-buildscan-recipes"]
image:http://img.shields.io/badge/license-ASF2-blue.svg["Apache License 2", link="http://www.apache.org/licenses/LICENSE-2.0.txt"]

This plugin enhances the information published in https://scans.gradle.com[Build Scans] with custom values and tags.

This https://scans.gradle.com/s/wjgfuwn447g2o[sample Build Scan] was generated using this plugin, for example, on Travis CI.
This https://scans.gradle.com/s/ovowowg7cathi[other one] was generated locally, using this plugin too: you will notice
that it is marked as `dirty` and shows the git status.

== Usage

Build script snippet for use in all Gradle versions:
[source,groovy]
[subs="attributes"]
.build.gradle
----
buildscript {
  repositories {
     maven {
        url "https://plugins.gradle.org/m2/"
     }
  }

  dependencies {
     classpath "com.gradle:build-scan-plugin:{buildscan-version}"
     classpath 'me.champeau.gradle:buildscan-recipes-plugin:{plugin-version}'
  }
}

apply plugin: 'com.gradle.build-scan'
apply plugin: me.champeau.gradle.buildscans.RecipesPlugin

buildScan {
   licenseAgreementUrl = 'https://gradle.com/terms-of-service'
   licenseAgree = 'yes'

   recipes 'git-commit', 'git-status', 'teamcity', 'gc-stats'
}
----

Build script snippet for new, incubating, plugin mechanism introduced in Gradle 2.1:
[source,groovy]
[subs="attributes"]
.build.gradle
----
plugins {
  id 'com.gradle.build-scan' version '{buildscan-version}'
  id 'me.champeau.buildscan-recipes' version '{plugin-version}'
}
----

== Configuration

The plugin provides a number of _recipes_ that can be used to automatically add tags and custom values to Build Scans.
The following recipes are available:

* `git-commit` : Tries to determine the Git commit ID for the build
* `git-status` : Outputs the result of `git status`, and tags the build as `dirty` if there are uncommitted or changes files locally
* `teamcity`   : Detects a build running under https://www.jetbrains.com/teamcity/[TeamCity], tags it as `CI`, and adds a link to the build
* `travis-ci`  : Detects a build running under https://travis-ci.org[Travis CI], tags it as `CI` and outputs information about the Travis environment
* `disk-usage` : Shows information about Gradle disk usage. It will scan your `$HOME/.gradle` directory as well as your project directory. Note that depending on your disk type, OS, disk usage and file system, this can turn to be very slow and add a non negligeable time at build start. You should therefore use this recipe with care. This recipe only works on Linux and Mac OS.
* `gc-stats`   : Shows statistics about garbage collection happening during your build.
* `messages`   : Allows adding ad-hoc values, tags and links from project properties (see below)

=== Recipe specific parameters

The `git-commit` recipe accepts an optional `baseUrl` parameter. If specified, a link to the commit will also be created. For example:

[source,groovy]
----
buildScan {
    recipe 'git-commit', baseUrl: 'https://github.com/melix/gradle-buildscan-recipes/tree'
}
----

The `teamcity` recipe accepts 2 optional parameters:
* `baseUrl` needs to be set to the CI server base URL
* `guest`, if set, will generate a URL with anonymous login

The `messages` recipe allows adding values, tags and links by convention. Any project property which starts with `buildScanValue` will be converted to a value. A property
 starting with `buildScanTag` will be converted to a tag, and `buildScanLink` into a link. For example:
* `gradle -PbuildScanValueMessage="Hello, World!"` will add a build scan value `Message` with value `Hello, World!`
* `gradle -PbuildScanTagHELLO will tag the build scan with `HELLO`
* `gradle -PbuildScanLinkGradle="https://www.gradle.org"` will add a link named `Gradle` pointing to `https://www.gradle.org`


== Adding recipes

Recipes are written in Groovy and can be found in the https://github.com/melix/gradle-buildscan-recipes/tree/master/src/recipes[recipes] directory. Note that the rules are _statically compiled_ and expose 2 variables:

* `buildScan`, of type `BuildScanExtension`, providing ability to tag a build scan, add a link, or add custom values
* `gradle`, giving access to the `Gradle` instance of the build
* `params`, a `Map<String, String>` of parameters (non-null, but maybe empty)

Recipes are bundled with this plugin.
